<?php

namespace Database\Factories;

use App\Models\Client;
use App\Models\Invoice;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Invoice>
 */
class InvoiceFactory extends Factory
{
    protected $model = Invoice::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $issueDate = fake()->dateTimeBetween('-60 days', 'now');
        $dueDate = (clone $issueDate)->modify('+30 days');

        return [
            'client_id' => Client::factory(),
            'user_id' => function (array $attributes) {
                return Client::find($attributes['client_id'])->user_id;
            },
            'invoice_number' => null, // Will be auto-generated by model boot
            'issue_date' => $issueDate,
            'due_date' => $dueDate,
            'subtotal' => 0,
            'tax_rate' => fake()->randomFloat(2, 0, 15),
            'tax_amount' => 0,
            'total' => 0,
            'status' => 'draft',
            'notes' => fake()->optional()->paragraph(),
        ];
    }

    /**
     * Indicate that the invoice has been sent.
     */
    public function sent(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'sent',
        ]);
    }

    /**
     * Indicate that the invoice has been paid.
     */
    public function paid(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'paid',
        ]);
    }

    /**
     * Indicate that the invoice is overdue.
     */
    public function overdue(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'overdue',
            'due_date' => now()->subDays(10),
        ]);
    }

    /**
     * Indicate that the invoice is cancelled.
     */
    public function cancelled(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'cancelled',
        ]);
    }

    /**
     * Set specific totals for the invoice.
     */
    public function withTotals(float $subtotal, ?float $taxRate = null): static
    {
        $taxRate = $taxRate ?? 0;
        $taxAmount = $subtotal * ($taxRate / 100);
        $total = $subtotal + $taxAmount;

        return $this->state(fn (array $attributes) => [
            'subtotal' => $subtotal,
            'tax_rate' => $taxRate,
            'tax_amount' => $taxAmount,
            'total' => $total,
        ]);
    }
}
